source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'sinatra', '1.3.0'
gem 'sinatra-contrib'
gem 'mysql2', '0.2.3'
gem 'addressable', '2.2.6'
gem 'em-mysqlplus', '0.1.5'
gem 'rack-flash3'
gem 'mysqlplus', '0.1.2'
gem 'sinatra-assetpack', :require => 'sinatra/assetpack'
gem 'rest-client'
gem 'daemon-kit'
gem 'twilio-ruby'