# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{keyhole}
  s.version = "0.1.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["buffpojken"]
  s.date = %q{2011-01-24}
  s.default_executable = %q{keyhole}
  s.description = %q{longer description of your gem}
  s.email = %q{daniel@sykewarrior.com}
  s.executables = ["keyhole"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "lib/em-websocket/connection.rb",
     "lib/em-websocket/debugger.rb",
     "lib/em-websocket/em-websocket.rb",
     "lib/em-websocket/handler.rb",
     "lib/em-websocket/handler75.rb",
     "lib/em-websocket/handler76.rb",
     "lib/em-websocket/handler_factory.rb",
     "lib/em-websocket/websocket.rb",
     "lib/keyhole.rb",
     "lib/query_server.rb",
     "lib/sat_parser.rb",
     "lib/webgui/lib/helpers.rb",
     "lib/webgui/models/device.rb",
     "lib/webgui/models/location.rb",
     "lib/webgui/models/session.rb",
     "lib/webgui/models/user.rb",
     "lib/webgui/views/_device_form.erb",
     "lib/webgui/views/_user_bar.erb",
     "lib/webgui/views/account.erb",
     "lib/webgui/views/configure.erb",
     "lib/webgui/views/edit_session.erb",
     "lib/webgui/views/frontpage.erb",
     "lib/webgui/views/layout.erb",
     "lib/webgui/views/map.erb",
     "lib/webgui/views/new_device.erb",
     "lib/webgui/views/new_session.erb",
     "lib/webgui/views/public/colorpicker/images/Thumbs.db",
     "lib/webgui/views/public/colorpicker/images/blank.gif",
     "lib/webgui/views/public/colorpicker/images/colorpicker_background.png",
     "lib/webgui/views/public/colorpicker/images/colorpicker_hex.png",
     "lib/webgui/views/public/colorpicker/images/colorpicker_hsb_b.png",
     "lib/webgui/views/public/colorpicker/images/colorpicker_hsb_h.png",
     "lib/webgui/views/public/colorpicker/images/colorpicker_hsb_s.png",
     "lib/webgui/views/public/colorpicker/images/colorpicker_indic.gif",
     "lib/webgui/views/public/colorpicker/images/colorpicker_overlay.png",
     "lib/webgui/views/public/colorpicker/images/colorpicker_rgb_b.png",
     "lib/webgui/views/public/colorpicker/images/colorpicker_rgb_g.png",
     "lib/webgui/views/public/colorpicker/images/colorpicker_rgb_r.png",
     "lib/webgui/views/public/colorpicker/images/colorpicker_select.gif",
     "lib/webgui/views/public/colorpicker/images/colorpicker_submit.png",
     "lib/webgui/views/public/colorpicker/images/custom_background.png",
     "lib/webgui/views/public/colorpicker/images/custom_hex.png",
     "lib/webgui/views/public/colorpicker/images/custom_hsb_b.png",
     "lib/webgui/views/public/colorpicker/images/custom_hsb_h.png",
     "lib/webgui/views/public/colorpicker/images/custom_hsb_s.png",
     "lib/webgui/views/public/colorpicker/images/custom_indic.gif",
     "lib/webgui/views/public/colorpicker/images/custom_rgb_b.png",
     "lib/webgui/views/public/colorpicker/images/custom_rgb_g.png",
     "lib/webgui/views/public/colorpicker/images/custom_rgb_r.png",
     "lib/webgui/views/public/colorpicker/images/custom_submit.png",
     "lib/webgui/views/public/colorpicker/images/select.png",
     "lib/webgui/views/public/colorpicker/images/select2.png",
     "lib/webgui/views/public/colorpicker/images/slider.png",
     "lib/webgui/views/public/colorpicker/js/colorpicker.js",
     "lib/webgui/views/public/colorpicker/js/eye.js",
     "lib/webgui/views/public/colorpicker/js/layout.js",
     "lib/webgui/views/public/colorpicker/js/utils.js",
     "lib/webgui/views/public/colorpicker/stylesheets/colorpicker.css",
     "lib/webgui/views/public/gsat.js",
     "lib/webgui/views/public/images/toolbar_mask.png",
     "lib/webgui/views/public/jquery142.js",
     "lib/webgui/views/public/main.css",
     "lib/webgui/views/public/map.css",
     "lib/webgui/views/public/style.css",
     "lib/webgui/views/public/style.ipad.css",
     "lib/webgui/views/public/style.ipad.landscape.css",
     "lib/webgui/views/public/style.ipad.portrait.css",
     "lib/webgui/webgui.rb"
  ]
  s.homepage = %q{http://github.com/buffpojken/keyhole}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{one-line summary of your gem}
  s.test_files = [
    "test/helper.rb",
     "test/test_keyhole.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

